data_path: ['dataset/1M/15k_in_1M_only_english_thr70_5k.json']
train_data: ''
valid_data: 'dataset/non_overlap/valid.json'
resume_from_checkpoint: ''
all_in_one: True
prompt_type: 3
if_train: True
split: False
split_by_prompt: True
extranal_data: True
if_concat : False
if_drop_duplicate: True
keep: 'last'
per_device_train_batch_size: 1
per_device_eval_batch_size: 1
learning_rate: 1.e-6
lr_end: 1.e-6
warmup_ratio: 0.1
warmup_steps: 10
num_train_epochs: 1
gradient_accumulation_steps: 4
logging_steps: 10
eval_steps: 2500
save_steps: 100
weight_decay: 1.e-5
MAX_INPUT: 1900
MODEL: 'google/gemma-2-9b-it'
dropout_rate: 0.1
awp_lr: 0
awp_eps: 1.e-4
awp_start_epoch: 0.5
label_smoothing_factor: 0
output_dir: 'output'
use_cache: False
token_type: 'MC'
lora_r: 32
lora_alpha: 64
lora_dropout: 0.05
test_mode: False
